### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by lgb1234727829** [jub0t/RoCAT#3]
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.resizeTemplate({0xc000010bc0, 0x36})
        C:/Users/User/Downloads/RoCAT-main/modules.go:63 +0x11b
main.downloadTemplate({0xc0002ea150?, 0x21?}, {0xc00000e348, 0x16})
        C:/Users/User/Downloads/RoCAT-main/api.go:167 +0x20a
main.main.func3(0xc0001782c0?)
        C:/Users/User/Downloads/RoCAT-main/main.go:142 +0x62f
github.com/urfave/cli/v2.(*Command).Run(0xc0001782c0, 0xc000048680, {0xc00004c320, 0x5, 0x5})
        C:/Users/User/go/pkg/mod/github.com/urfave/cli/v2@v2.24.3/command.go:273 +0x9eb
github.com/urfave/cli/v2.(*Command).Run(0xc0001786e0, 0xc0000485c0, {0xc000102000, 0x6, 0x8})
        C:/Users/User/go/pkg/mod/github.com/urfave/cli/v2@v2.24.3/command.go:266 +0xc4d
github.com/urfave/cli/v2.(*App).RunContext(0xc000176000, {0x759d08?, 0xc000014130}, {0xc000102000, 0x6, 0x8})
        C:/Users/User/go/pkg/mod/github.com/urfave/cli/v2@v2.24.3/app.go:332 +0x616
github.com/urfave/cli/v2.(*App).Run(...)
        C:/Users/User/go/pkg/mod/github.com/urfave/cli/v2@v2.24.3/app.go:309
main.main()
        C:/Users/User/Downloads/RoCAT-main/main.go:261 +0xc6d

**Comment by jareer12** [comment]
I'll look into this, can you prove anything else?
